export type AvailableSocialMedia =
  | "codewars"
  | "codepen"
  | "devto"
  | "facebook"
  | "freecodecamp"
  | "frontendmentor"
  | "gitlab"
  | "github"
  | "hashnode"
  | "linkedin"
  | "stackoverflow"
  | "twitter"
  | "twitch"
  | "youtube";
